services:
  staging_db:
    image: postgres:latest
    hostname: staging_bank_marketing
    container_name: staging_bank_marketing_container
    restart: on-failure
    environment:
      - POSTGRES_DB=staging
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cobapassword
    volumes:
      - ./marketing_staging/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5436:5432
    networks:
      - my_network

  warehouse_db:
    image: postgres:latest
    hostname: warehouse_bank_marketing
    container_name: warehouse_bank_marketing_container
    restart: on-failure
    environment:
      - POSTGRES_DB=warehouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cobapassword
    volumes:
      - ./marketing_warehouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5437:5432
    networks:
      - my_network

networks:
  my_network:
    driver: bridge